export const TOGGLE_MODE = 'TOGGLE_MODE';
export const REQUEST_REPOS = 'REQUEST_REPOS';
export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS';
export const GET_REPOS_FALUER = 'GET_REPOS_FALUER';
export const SET_PICKER_VALUE = 'SET_PICKER_VALUE';
